language: go

go:
  - 1.21.x

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - make docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
