name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/docker/library/golang:alpine
    steps:
      - name: Install Git
        run: apk add --no-cache git

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: apk add --no-cache git gcc musl-dev

      - name: Go Mod
        run: go mod download

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: false
